:Author: ryan_habis
:Email: {ryan.habis@gmail.com}
:Date: 21/04/2022
:Revision: version#
:License: Public Domain

= Project: {Tempreture and humibary monitor}

== Step 1: components needed list:

1. 3 - wires
2. 1 - DHT11 Temperature and Humidity Module Sensory (3 pin)
3. 1 - Breadboard
4. 1 - Arduino Uno
== Step 2: Assemble the circuit

1. connect the DHT11 Temperature and Humidity Module Sensory (3 pin) to the breadboard
2. Connect the DHT11 signal to Digital 7 on the arduino uno with a wire through the breadboard. 
3. Connect the DHT11 positive pin to the 5 volt on the arduino uno with a wire through the breadboard.
4. Connect the DHT11 negative pin to ground on the arduino uno with a wire through the breadboard.

Below is a picture of the DHT11 Temperature and Humidity Module Sensory (3 pin)
https://www.circuitbasics.com/wp-content/uploads/2015/12/DHT11-Pinout-for-three-pin-and-four-pin-types-2.jpg

Below is the Wiring Diagram
https://www.circuitbasics.com/wp-content/uploads/2015/10/Arduino-DHT11-Tutorial-3-Pin-DHT11-Wiring-Diagram-768x391.png

== Step 3: Load the code

Copy and paste the code.

=== License
This project is released under a {Scott Campbell | Arduino} License.

https://www.circuitbasics.com/how-to-set-up-the-dht11-humidity-sensor-on-an-arduino/

=== Contributing
To contribute to this project please contact ryan_habis https://id.arduino.cc/ryan_habis

